# Generated by Django 3.0.5 on 2020-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='computer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='row',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
