# Generated by Django 3.0.5 on 2020-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0006_auto_20200802_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='row',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
