# Generated by Django 3.0.5 on 2020-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0007_auto_20200802_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='row',
            field=models.BooleanField(default=False),
        ),
    ]
