# Generated by Django 3.0.5 on 2020-08-03 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0008_auto_20200802_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='row',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='turn1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None, null=True), blank=True, null=True, size=None),
        ),
    ]
