# Generated by Django 3.0.9 on 2020-08-04 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0010_auto_20200803_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='starter',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
