# Generated by Django 3.0.9 on 2020-08-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0012_gamehistory_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='counter',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
