# Generated by Django 3.0.9 on 2020-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0013_auto_20200805_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=255, null=True)),
                ('userPlayer', models.CharField(max_length=255, null=True)),
                ('computerPlayer', models.CharField(max_length=255, null=True)),
                ('this_turn_player', models.CharField(max_length=255, null=True)),
                ('turn', models.CharField(max_length=255, null=True)),
                ('items', models.CharField(max_length=255, null=True)),
                ('result', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
