# Generated by Django 3.0.9 on 2020-08-23 16:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0014_mainobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainobject',
            name='computerPlayer',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='items',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='result',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='starter',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='this_turn_player',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='turn',
        ),
        migrations.RemoveField(
            model_name='mainobject',
            name='userPlayer',
        ),
        migrations.AddField(
            model_name='mainobject',
            name='mainObject',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
