# Generated by Django 3.0.9 on 2020-08-24 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0015_auto_20200823_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainobject',
            name='mainObject',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
