# Generated by Django 3.0.9 on 2020-08-24 11:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('dooz', '0017_auto_20200824_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainobject',
            name='mainObject',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
